repositories = ["sensu-plugins/sensu-plugin",
"sensu-plugins/sensu-plugin-spec",
"sensu-plugins/sensu-plugins-datadog",
"sensu-plugins/sensu-plugins-process-checks",
"sensu-plugins/sensu-plugins-disk-checks",
"sensu-plugins/sensu-plugins-nginx",
"sensu-plugins/sensu-plugins-raid-checks",
"sensu-plugins/sensu-plugins-aws",
"sensu-plugins/sensu-plugins-network-checks",
"sensu-plugins/sensu-plugins-campfire",
"sensu-plugins/sensu-plugins-hipchat",
"sensu-plugins/sensu-plugins-pagerduty",
"sensu-plugins/sensu-plugins-apache",
"sensu-plugins/sensu-plugins-dhcp",
"sensu-plugins/sensu-plugins-docker",
"sensu-plugins/sensu-plugins-dns",
"sensu-plugins/sensu-plugins-consul",
"sensu-plugins/sensu-plugins-couchbase",
"sensu-plugins/sensu-plugins-cassandra",
"sensu-plugins/sensu-plugins-mesos",
"sensu-plugins/sensu-plugins-mongodb",
"sensu-plugins/sensu-plugins-memcached",
"sensu-plugins/sensu-plugins-mysql",
"sensu-plugins/sensu-plugins-lxc",
"sensu-plugins/sensu-plugins-java",
"sensu-plugins/sensu-plugins-kannel",
"sensu-plugins/sensu-plugins-jenkins",
"sensu-plugins/sensu-plugins-influxdb",
"sensu-plugins/sensu-plugins-gpg",
"sensu-plugins/sensu-plugins-etcd",
"sensu-plugins/sensu-plugins-github",
"sensu-plugins/sensu-plugins-graphite",
"sensu-plugins/sensu-plugins-ssl",
"sensu-plugins/sensu-plugins-redis",
"sensu-plugins/sensu-plugins-rabbitmq",
"sensu-plugins/sensu-plugins-puma",
"sensu-plugins/sensu-plugins-windows",
"sensu-plugins/sensu-plugins-varnish",
"sensu-plugins/sensu-plugins-uchiwa",
"sensu-plugins/sensu-plugins-postgres",
"sensu-plugins/sensu-plugins-postfix",
"sensu-plugins/sensu-plugins-openstack",
"sensu-plugins/sensu-plugins-monit",
"sensu-plugins/sensu-plugins-fluentd",
"sensu-plugins/sensu-plugins-newrelic",
"sensu-plugins/sensu-plugins-haproxy",
"sensu-plugins/sensu-plugins-elasticsearch",
"sensu-plugins/sensu-plugins-unicorn",
"sensu-plugins/sensu-plugins-twilio",
"sensu-plugins/sensu-plugins-twemproxy",
"sensu-plugins/sensu-plugins-trafficserver",
"sensu-plugins/sensu-plugins-telapi",
"sensu-plugins/sensu-plugins-cpu-checks",
"sensu-plugins/sensu-plugins-memory-checks",
"sensu-plugins/sensu-plugins-syslog-ng",
"sensu-plugins/sensu-plugins-supervisor",
"sensu-plugins/sensu-plugins-springboot",
"sensu-plugins/sensu-plugins-solr",
"sensu-plugins/sensu-plugins-snmp",
"sensu-plugins/sensu-plugins-sip",
"sensu-plugins/sensu-plugins-sftp",
"sensu-plugins/sensu-plugins-serverspec",
"sensu-plugins/sensu-plugins-sensu",
"sensu-plugins/sensu-plugins-selinux",
"sensu-plugins/sensu-plugins-rspec",
"sensu-plugins/sensu-plugins-riak",
"sensu-plugins/sensu-plugins-resque",
"sensu-plugins/sensu-plugins-qmail",
"sensu-plugins/sensu-plugins-pingdom",
"sensu-plugins/sensu-plugins-php-fpm",
"sensu-plugins/sensu-plugins-percona",
"sensu-plugins/sensu-plugins-pacemaker",
"sensu-plugins/sensu-plugins-opsgenie",
"sensu-plugins/sensu-plugins-openvpn",
"sensu-plugins/sensu-plugins-openldap",
"sensu-plugins/sensu-plugins-nbzget",
"sensu-plugins/sensu-plugins-logs",
"sensu-plugins/sensu-plugins-ipmi",
"sensu-plugins/sensu-plugins-imap",
"sensu-plugins/sensu-plugins-icecast",
"sensu-plugins/sensu-plugins-http",
"sensu-plugins/sensu-plugins-hbase",
"sensu-plugins/sensu-plugins-growthforecast",
"sensu-plugins/sensu-plugins-graylog",
"sensu-plugins/sensu-plugins-gluster",
"sensu-plugins/sensu-plugins-ftp",
"sensu-plugins/sensu-plugins-filesystem-checks",
"sensu-plugins/sensu-plugins-eye",
"sensu-plugins/sensu-plugins-erlang",
"sensu-plugins/sensu-plugins-cucumber",
"sensu-plugins/sensu-plugins-chef",
"sensu-plugins/sensu-plugins-tripwire",
"sensu-plugins/sensu-plugins-ceph",
"sensu-plugins/sensu-plugins-beanstalk",
"sensu-plugins/sensu-plugins-ansible",
"sensu-plugins/sensu-plugins-officehours",
"sensu-plugins/sensu-plugins-victorops",
"sensu-plugins/sensu-plugins-twitter",
"sensu-plugins/sensu-plugins-slack",
"sensu-plugins/sensu-plugins-mailer",
"sensu-plugins/sensu-plugins-logstash",
"sensu-plugins/sensu-plugins-irc",
"sensu-plugins/sensu-plugins-ponymailer",
"sensu-plugins/sensu-plugins-splunk",
"sensu-plugins/sensu-plugins-dashing",
"sensu-plugins/sensu-plugins-clockworksms",
"sensu-plugins/sensu-plugins-sentry",
"sensu-plugins/sensu-plugins-gelf",
"sensu-plugins/sensu-plugins-hubot",
"sensu-plugins/sensu-plugins-flowdock",
"sensu-plugins/sensu-plugins-xmpp",
"sensu-plugins/sensu-plugins-eep",
"sensu-plugins/sensu-plugins-google-spreadsheet",
"sensu-plugins/sensu-plugins-imkayac",
"sensu-plugins/sensu-plugins-pushover",
"sensu-plugins/sensu-plugins-messagemedia",
"sensu-plugins/sensu-plugins-request-tracker",
"sensu-plugins/sensu-plugins-zendesk",
"sensu-plugins/sensu-plugins-statuspage",
"sensu-plugins/sensu-plugins-tempodb",
"sensu-plugins/sensu-plugins-skyline",
"sensu-plugins/sensu-plugins-opentsdb",
"sensu-plugins/sensu-plugins-mackerel",
"sensu-plugins/sensu-plugins-librato",
"sensu-plugins/sensu-plugins-geckoboard",
"sensu-plugins/sensu-plugins-execute",
"sensu-plugins/sensu-plugins-load-checks",
"sensu-plugins/sensu-plugins-nvidia",
"sensu-plugins/sensu-plugins-bluepill",
"sensu-plugins/sensu-plugins-conntrack",
"sensu-plugins/sensu-plugins-entropy-checks",
"sensu-plugins/sensu-plugins-io-checks",
"sensu-plugins/sensu-plugins-ntp",
"sensu-plugins/sensu-plugins-uptime-checks",
"sensu-plugins/sensu-plugins-cgroups",
"sensu-plugins/sensu-plugins-vmstats",
"sensu-plugins/sensu-plugins-hardware",
"sensu-plugins/sensu-plugins-environmental-checks",
"sensu-plugins/sensu-plugins-xen",
"sensu-plugins/sensu-plugins-ipvs",
"sensu-plugins/sensu-plugins-zookeeper",
"sensu-plugins/sensu-plugins-golang",
"sensu-plugins/sensu-plugins-sms",
"sensu-plugins/sensu-plugins-wordpress",
"sensu-plugins/sensu-plugins-netscaler",
"sensu-plugins/sensu-plugins-kegbot",
"sensu-plugins/sensu-plugins-sidekiq",
"sensu-plugins/sensu-plugins-puppet",
"sensu-plugins/sensu-plugins-iis",
"sensu-plugins/sensu-plugins-strongswan",
"sensu-plugins/sensu-plugins-ups",
"sensu-plugins/sensu-plugins-ubiquiti",
"sensu-plugins/sensu-plugins-rethinkdb",
"sensu-plugins/sensu-plugins-couchdb",
"sensu-plugins/sensu-plugins-freeradius",
"sensu-plugins/sensu-plugins-riemann",
"sensu-plugins/sensu-plugins-chrony",
"sensu-plugins/sensu-plugins-kubernetes",
"sensu-plugins/sensu-plugins-mailgun",
"sensu-plugins/sensu-plugins-telegram",
"sensu-plugins/sensu-plugins-chatwork",
"sensu-plugins/sensu-plugins-gearman",
"sensu-plugins/sensu-plugins-lvm",
"sensu-plugins/sensu-plugins-systemd",
"sensu-plugins/sensu-plugins-bigpanda",
"sensu-plugins/sensu-plugins-jolokia",
"sensu-plugins/sensu-plugins-zfs",
"sensu-plugins/sensu-plugins-switchvox",
"sensu-plugins/sensu-plugins-skel",
"sensu-plugins/sensu-plugins-dovecot",
"sensu-plugins/sensu-plugins-tomcat",
"sensu-plugins/sensu-plugins-nrpe",
"sensu-plugins/sensu-plugins-vsphere",
"sensu-plugins/sensu-plugins-signifai",
"sensu-plugins/sensu-plugins-ldap",
"sensu-plugins/maintainers-governance",
"sensu-plugins/sensu-plugins-dcos",
"sensu-plugins/sensu-plugins-pdns",
"sensu-plugins/sensu-pg",
"sensu-plugins/sensu-plugins-vault",
"sensu-plugins/sensu-plugins-microsoft-teams",
"sensu-plugins/sensu-plugins-stackstorm"]

####              ####
####  All Types   ####
####              ####

[[label]]
color = "e11d21"
name = "Type: Bug"
mappings = ["bug"]

[[label]]
color = "d4c5f9"
name = "Type: Enhancement"
mappings = ["enhancement"]

[[label]]
color = "d4c5f9"
name = "Type: Question"
mappings = ["question", "questions"]

[[label]]
color = "d4c5f9"
name = "Type: Proposal"
mappings = ["Proposal", "RFC"]

[[label]]
color = "d4c5f9"
name = "Type: Documentation"
mappings = ["Documentation", "Docs"]


####              ####
#### All Statuses ####
####              ####

[[label]]
color = "fef2c0"
name = "Status: On Hold"
mappings = ["On Hold"]

[[label]]
color = "fef2c0"
name = "Status: Feedback Requested"
mappings = ["Feedback Requested"]

[[label]]
color = "fef2c0"
name = "Status: Needs Test Artifact"
# mappings = [""]

[[label]]
color = "fef2c0"
name = "Status: Needs Changelog"
# mappings = [""]

[[label]]
color = "c2e0c6"
name = "Status: In Progress"
mappings = ["In Progress"]

[[label]]
color = "fef2c0"
name = "Status: Needs Review"
mappings = ["Investigation Required", "Needs Review", "Review Needed"]

[[label]]
color = "fef2c0"
name = "Status: Blocked"
mappings = ["Blocked"]

[[label]]
color = "fef2c0"
name = "Status: Needs Rebase"
mappings = ["Rebase"]

[[label]]
color = "fef2c0"
name = "Status: Upstream Change Required"
mappings = ["Upstream Change Required"]

[[label]]
color = "fef2c0"
name = "Status: Awaiting Response"
mappings = ["Awaiting Response"]

[[label]]
color = "fef2c0"
name = "Status: Needs SME Review"
# mappings = [""]

[[label]]
color = "000000"
name = "Status: Abandoned"
mappings = ["Abandoned"]

[[label]]
color = "000000"
name = "Status: Stale"
mappings = ["Stale"]


[[label]]
color = "000000"
name = "Status: Thinking"
mappings = ["Thinking"]

[[label]]
color = "000000"
name = "Status: Wrong Repo"
mappings = ["Wrong Repo"]

[[label]]
color = "000000"
name = "Status: Won't Fix"
mappings = ["wontfix", "Won't Fix"]

#######
## Two special cases for getting people's involvement.
######

[[label]]
color = "c2e0c6"
name = "Status: Help Wanted"
mappings = ["help wanted"]

[[label]]
color = "c2e0c6"
name = "Status: Claimed"

####              ####
####  All Areas   ####
####              ####

[[label]]
color = "006b75"
name = "Area: Check"
# mappings = [""]

[[label]]
color = "006b75"
name = "Area: Metric"
# mappings = [""]

[[label]]
color = "006b75"
name = "Area: Handler"
# mappings = [""]

[[label]]
color = "006b75"
name = "Area: Mutator"
# mappings = [""]

[[label]]
color = "006b75"
name = "Area: Extension"
# mappings = [""]

####                   ####
####  All Platforms    ####
####                   ####

[[label]]
color = "bfd4f2"
name = "Platform: BSD"
mappings = ["BSD"]

[[label]]
color = "bfd4f2"
name = "Platform: Solaris"
mappings = ["Solaris"]

[[label]]
color = "bfd4f2"
name = "Platform: MacOS"
mappings = ["MacOS"]

[[label]]
color = "bfd4f2"
name = "Platform: Windows"
mappings = ["Windows"]


####                   ####
####  All Priorities   ####
####                   ####

[[label]]
color = "ededed"
name = "Priority: Low"
# mappings = [""]

[[label]]
color = "eb6420"
name = "Priority: High"
# mappings = [""]

[[label]]
color = "e11d21"
name = "Priority: Critical"
# mappings = [""]

####                ####
####  All Impact    ####
####                ####

[[label]]
color = "fc2929"
name = "Impact: Regression"
# mappings = [""]

[[label]]
color = "fc2929"
name = "Impact: Breaking Change"
# mappings = [""]

####               ####
####  All others   ####
####               ####

############## Delete Defaults ##############

[[label]]
delete = true
name = "duplicate"

[[label]]
delete = true
name = "invalid"
