repositories = ["sensu-plugins/sensu-plugins-twilio"]

####              ####
####  All Types   ####
####              ####

[[label]]
color = "e11d21"
name = "Type: Bug"
mappings = ["bug", "Bug"]

[[label]]
color = "d4c5f9"
name = "Type: Enhancement"
mappings = ["enhancement", "Enhancement"]

[[label]]
color = "d4c5f9"
name = "Type: Question"
mappings = ["question", "questions"]

[[label]]
color = "d4c5f9"
name = "Type: Proposal"
mappings = ["Proposal", "RFC"]

[[label]]
color = "d4c5f9"
name = "Type: Documentation"
mappings = ["Documentation", "Docs"]


####              ####
#### All Statuses ####
####              ####

[[label]]
color = "fef2c0"
name = "Status: On Hold"
mappings = ["On Hold"]

[[label]]
color = "fef2c0"
name = "Status: Feedback Requested"
mappings = ["Feedback Requested"]

[[label]]
color = "fef2c0"
name = "Status: Needs Test Artifact"
# mappings = [""]

[[label]]
color = "fef2c0"
name = "Status: Needs Changelog"
# mappings = [""]

[[label]]
color = "c2e0c6"
name = "Status: In Progress"
mappings = ["In Progress"]

[[label]]
color = "fef2c0"
name = "Status: Needs Review"
mappings = ["Investigation Required", "Needs Review", "Review Needed"]

[[label]]
color = "fef2c0"
name = "Status: Blocked"
mappings = ["Blocked"]

[[label]]
color = "fef2c0"
name = "Status: Needs Rebase"
mappings = ["Rebase"]

[[label]]
color = "fef2c0"
name = "Status: Upstream Change Required"
mappings = ["Upstream Change Required"]

[[label]]
color = "fef2c0"
name = "Status: Awaiting Response"
mappings = ["Awaiting Response"]

[[label]]
color = "fef2c0"
name = "Status: Needs SME Review"
# mappings = [""]

[[label]]
color = "000000"
name = "Status: Abandoned"
mappings = ["Abandoned"]

[[label]]
color = "000000"
name = "Status: Stale"
mappings = ["Stale"]


[[label]]
color = "000000"
name = "Status: Thinking"
mappings = ["Thinking"]

[[label]]
color = "000000"
name = "Status: Wrong Repo"
mappings = ["Wrong Repo"]

[[label]]
color = "000000"
name = "Status: Won't Fix"
mappings = ["wontfix", "Won't Fix"]

#######
## Two special cases for getting people's involvement.
######

[[label]]
color = "c2e0c6"
name = "Status: Help Wanted"
mappings = ["help wanted", "Help Wanted"]

[[label]]
color = "c2e0c6"
name = "Status: Claimed"

####              ####
####  All Areas   ####
####              ####

[[label]]
color = "006b75"
name = "Area: Check"
# mappings = [""]

[[label]]
color = "006b75"
name = "Area: Metric"
# mappings = [""]

[[label]]
color = "006b75"
name = "Area: Handler"
# mappings = [""]

[[label]]
color = "006b75"
name = "Area: Mutator"
# mappings = [""]

[[label]]
color = "006b75"
name = "Area: Extension"
# mappings = [""]

####                   ####
####  All Platforms    ####
####                   ####

[[label]]
color = "bfd4f2"
name = "Platform: BSD"
mappings = ["BSD"]

[[label]]
color = "bfd4f2"
name = "Platform: Solaris"
mappings = ["Solaris"]

[[label]]
color = "bfd4f2"
name = "Platform: MacOS"
mappings = ["MacOS"]

[[label]]
color = "bfd4f2"
name = "Platform: Windows"
mappings = ["Windows"]


####                   ####
####  All Priorities   ####
####                   ####

[[label]]
color = "ededed"
name = "Priority: Low"
# mappings = [""]

[[label]]
color = "eb6420"
name = "Priority: High"
# mappings = [""]

[[label]]
color = "e11d21"
name = "Priority: Critical"
# mappings = [""]

####                ####
####  All Impact    ####
####                ####

[[label]]
color = "fc2929"
name = "Impact: Regression"
# mappings = [""]

[[label]]
color = "fc2929"
name = "Impact: Breaking Change"
# mappings = [""]

####               ####
####  All others   ####
####               ####

############## Delete Defaults ##############

[[label]]
delete = true
name = "duplicate"

[[label]]
delete = true
name = "invalid"
